export interface EscopoItem {
  id: string;
  ordem: number;
  atividade: string;
  metodologia: string;
}

export interface MaterialItem {
  id: string;
  descricao: string;
  especificacao: string;
  quantidade: string;
  unidade: string;
}

export interface MedicaoItem {
  id: string;
  parametro: string;
  antes: string;
  depois: string;
  limite: string;
}

export interface NaoConformidadeItem {
  id: string;
  problema: string;
  norma: string;
  tratamento: string;
  prazo: string;
}

export interface UploadedImage {
  name: string;
  data: string; // base64
  description: string;
}

export interface ArtManutencaoParams {
  documentNumber: string;
  artNumber: string;
  clientName: string;
  cnpj: string;
  address: string;
  bairro: string;
  city: string;
  uf: string;
  email: string;
  telefone: string;
  
  // RT VL Engenharia Info
  rtName: string;
  rtCrea: string;
  rtEmail: string;
  rtTelefone: string;
  rtArt: string;

  // Equipment & Service Info
  serviceType: "PREVENTIVA" | "CORRETIVA" | "PREDITIVA" | "REFORMA" | "INSPEÇÃO";
  equipmentName: string;
  equipmentType: string;
  equipmentTag: string;
  problemDescription: string;
  issueDate: string;
  validityDate: string;
  startDate: string;
  endDate: string;
  contractValue: string;
  localExecucao: string;
  cepExecucao: string;
  durationHours: string;
  codigoAtividadeConfea: string;
  areaAtuacao: string;
  modalidade: string;

  // Texts generated by AI
  introducao: string;
  objetivo: string;
  justificativa: string;
  conclusao: string;
  ferramentas: string;
  qualificacaoEquipe: string;
  criteriosAceitacao: string;
  proximaManutencao: string;
  pendencias: string;
  testesComissionamento: string;
}

export const PREFILLED_ART_PARAMS: ArtManutencaoParams = {
  documentNumber: "MDM-2026-042",
  artNumber: "PE20261198422",
  clientName: "Indústrias Metalúrgicas Nordeste S.A.",
  cnpj: "12.345.678/0001-99",
  address: "Av. Industrial, nº 1500, Distrito Industrial",
  bairro: "Cabo de Santo Agostinho",
  city: "Cabo de Santo Agostinho",
  uf: "PE",
  email: "manutencao@metalnordeste.com.br",
  telefone: "(81) 3451-9900",

  // RT VL Engenharia Info
  rtName: "Eng. Mecânico Vitor Leonardo",
  rtCrea: "1822299490 – PE",
  rtEmail: "vitorleonardocl@gmail.com",
  rtTelefone: "(81) 98444-2592",
  rtArt: "ART-PE-1822299490",

  // Equipment & Service Info
  serviceType: "PREVENTIVA",
  equipmentName: "Compressor de Parafuso Rotativo 75HP",
  equipmentType: "Compressores e Sistemas Pneumáticos",
  equipmentTag: "CMP-04",
  problemDescription: "Manutenção preventiva programada de 4.000 horas, com substituição de kit de filtros, óleo lubrificante sintético, inspeção das válvulas e calibração de pressostatos e sensores térmicos.",
  issueDate: "04/07/2026",
  validityDate: "04/07/2027",
  startDate: "01/07/2026",
  endDate: "03/07/2026",
  contractValue: "R$ 12.850,00",
  localExecucao: "Av. Industrial, nº 1500, Distrito Industrial, Cabo de Santo Agostinho - PE",
  cepExecucao: "54505-000",
  durationHours: "24",
  codigoAtividadeConfea: "A1120 - Manutenção e Reparação de Máquinas e Equipamentos",
  areaAtuacao: "Engenharia Mecânica",
  modalidade: "Execução de Serviço Técnico",

  // Texts generated by AI or prefilled
  introducao: "O presente Memorial Descritivo e Relatório Técnico documentam a inspeção, manutenção técnica e comissionamento do compressor rotativo de parafusosCMP-04 de 75HP da contratante Indústrias Metalúrgicas Nordeste S.A., em total consonância com as prescrições normativas da NR-12 (Segurança em Máquinas e Equipamentos) e NR-13 (Vasos de Pressão), bem como orientações operacionais do fabricante.",
  objetivo: "Garantir a confiabilidade operacional e a integridade estrutural do sistema de geração de ar comprimido, assegurando a continuidade de abastecimento pneumático do pavilhão de fundição e mitigando riscos de falhas catastróficas ou incidentes de segurança industrial.",
  justificativa: "A manutenção preventiva de 4.000 horas é um requisito mandatório para assegurar a eficiência termodinâmica do compressor de parafusos, prevenindo desgaste prematuro dos rotores, contaminação por condensado e sobreaquecimento da unidade compressora.",
  conclusao: "Consideramos os serviços de manutenção executados como plenamente CONCLUÍDOS E APROVADOS. O compressor CMP-04 encontra-se operando em perfeitas condições de estabilidade térmica, pressórica e vibracional, estando integralmente liberado para operação em regime contínuo.",
  ferramentas: "Torquímetro estalador calibrado, bomba de vácuo, manifold digital, multímetro TrueRMS, megômetro, saca-filtros pneumático, trena laser, termovisor FLIR, analisador de vibração triaxial e EPIs completos.",
  qualificacaoEquipe: "Engenheiro Mecânico Responsável (CREA ativo), Técnico em Eletromecânica com capacitação em NR-10 (Segurança Elétrica) e NR-12 (Segurança em Máquinas), e Auxiliar Técnico com treinamento em LOTO (Lockout/Tagout).",
  criteriosAceitacao: "1. Partida suave sem ruídos metálicos ou vibração anômala.\n2. Estabilização da temperatura da unidade compressora entre 82ºC e 88ºC.\n3. Ausência absoluta de vazamentos de óleo ou ar pneumático em conexões e mangueiras.\n4. Corrente elétrica de consumo nos limites nominais do motor.",
  proximaManutencao: "Recomenda-se a realização da próxima parada preventiva em 1.000 horas (ou 3 meses) para substituição do pré-filtro de admissão de ar e coleta de amostra de óleo para análise de espectrometria.",
  pendencias: "Nenhuma pendência operacional registrada. Todas as atividades propostas no escopo técnico original foram integralmente executadas.",
  testesComissionamento: "Foram executados testes de partida em vazio, teste de transição de carga (carga/alívio), simulação de desarme por alta temperatura de óleo (atuando a 110ºC) e aferição da válvula de segurança conforme protocolo de segurança da NR-13."
};

export const PREFILLED_ESCOPO: EscopoItem[] = [
  {
    id: "esc_1",
    ordem: 1,
    atividade: "Mobilização de Equipe e Execução de LOTO (Bloqueio)",
    metodologia: "Aplicação do procedimento de Lockout/Tagout no disjuntor de força geral do compressor CMP-04 com cadeado individual e etiqueta de sinalização pericial da VL Engenharia."
  },
  {
    id: "esc_2",
    ordem: 2,
    atividade: "Drenagem e Substituição do Óleo Lubrificante",
    metodologia: "Aquecimento prévio do equipamento, despressurização total do reservatório de ar/óleo, drenagem completa do óleo saturado e abastecimento com óleo sintético de alta performance para 4.000 horas."
  },
  {
    id: "esc_3",
    ordem: 3,
    atividade: "Substituição do Elemento Separador de Ar/Óleo",
    metodologia: "Desmontagem da tampa do vaso separador (NR-13), remoção cuidadosa do elemento exaurido, limpeza das superfícies de vedação e montagem do novo elemento separador com juntas novas e cabo de aterramento estático."
  },
  {
    id: "esc_4",
    ordem: 4,
    atividade: "Limpeza Física dos Radiadores de Ar e Óleo",
    metodologia: "Aplicação de jato de ar comprimido e desengraxante biodegradável nas aletas do radiador para remoção de poeiras industriais e fuligens acumuladas que prejudicam a troca de calor."
  },
  {
    id: "esc_5",
    ordem: 5,
    atividade: "Inspeção e Reaperto de Conexões Elétricas",
    metodologia: "Termografia prévia com câmera infravermelha, seguida de reaperto de todos os bornes de contato e contatores no painel elétrico utilizando chaves isoladas (NR-10)."
  },
  {
    id: "esc_6",
    ordem: 6,
    atividade: "Comissionamento e Partida de Teste",
    metodologia: "Retirada do bloqueio LOTO, verificação de sentido de rotação do motor principal, verificação de ruídos e monitoramento da rampa de elevação de pressão operacional até o desarme."
  }
];

export const PREFILLED_MATERIAIS: MaterialItem[] = [
  {
    id: "mat_1",
    descricao: "Óleo Sintético para Compressor de Parafuso",
    especificacao: "Lubrificante Sintético ISO VG 46 - Long Life",
    quantidade: "20",
    unidade: "Litros"
  },
  {
    id: "mat_2",
    descricao: "Filtro de Óleo Spin-On",
    especificacao: "Filtro blindado de alta vazão e retenção micrométrica",
    quantidade: "1",
    unidade: "Peça"
  },
  {
    id: "mat_3",
    descricao: "Filtro de Admissão de Ar",
    especificacao: "Filtro de celulose plissada de alta eficiência",
    quantidade: "1",
    unidade: "Peça"
  },
  {
    id: "mat_4",
    descricao: "Elemento Separador Ar/Óleo",
    especificacao: "Filtro coalescente de manta de microfibra de vidro",
    quantidade: "1",
    unidade: "Peça"
  }
];

export const PREFILLED_MEDICOES: MedicaoItem[] = [
  {
    id: "med_1",
    parametro: "Pressão de Operação Máxima (Descarga)",
    antes: "7.8 bar",
    depois: "8.5 bar",
    limite: "8.5 bar"
  },
  {
    id: "med_2",
    parametro: "Temperatura do Óleo na Unidade Compressora",
    antes: "98.5 ºC",
    depois: "84.2 ºC",
    limite: "< 105 ºC"
  },
  {
    id: "med_3",
    parametro: "Corrente Elétrica do Motor Principal (Fase R)",
    antes: "92.4 A",
    depois: "88.1 A",
    limite: "96.0 A"
  },
  {
    id: "med_4",
    parametro: "Resistência de Isolamento do Motor (Megômetro)",
    antes: "150 MΩ",
    depois: "450 MΩ",
    limite: "> 50 MΩ"
  }
];

export const PREFILLED_NAO_CONFORMIDADES: NaoConformidadeItem[] = [
  {
    id: "nc_1",
    problema: "Termografia detectou ponto quente (85ºC) no contato da fase S do contator principal de força devido a folga de aperto.",
    norma: "NR-10 Item 10.4.4.1 (Inspeção periódica e eliminação de aquecimentos anômalos)",
    tratamento: "Substituição do contator de força de 95A e crimpagem de novos terminais tubulares na fiação.",
    prazo: "Imediato (Resolvido no ato)"
  },
  {
    id: "nc_2",
    problema: "Linha de drenagem de condensado do pulmão de ar descarregando direto no solo sem caixa separadora de água-óleo.",
    norma: "Resolução CONAMA nº 357/2005 (Proibição de descarte de óleos na rede pluvial ou solo)",
    tratamento: "Recomendado à contratante adquirir e instalar módulo separador de condensado coalescente.",
    prazo: "30 dias"
  }
];
